engines:
  radon:
    enabled: true

  duplication:
    enabled: true
    config:
      languages:
      - python
    exclude_fingerprints:
  FIXME:
    enabled: true

ratings:
  paths:
  - nslocalizer/

exclude_paths:
- examples/
- tests/
- tools/
- "*.md"
- "*.yml"
- "*.ini"
- Makefile
- Dangerfile
- Gemfile
- LICENSE
- contributing/
- docs/
- setup.py
- nslocalizer.py